version: '3.4'
name: DragaliaAPI

volumes:
  sqlvolume:
    name: ${VOLUME_ID}

services:
  dragaliaapi:
    container_name: dragaliaapi
    hostname: dragaliaapi
    image: ${DOCKER_REGISTRY-}dragaliaapi
    build:
      context: .
      dockerfile: DragaliaAPI/Dockerfile
    ports:
      - "5000:80"
      - "5001:443"
    links:
      - sqlserver
    
  sqlserver:
    container_name: sqlserver
    hostname: sqlserver
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - "MSSQL_SA_PASSWORD=DragaliaLost123"
      - "ACCEPT_EULA=Y"
    ports:
      - "1433:1433"
    volumes:
      - sqlvolume:/var/opt/mssql

  redis:
    container_name: redis
    hostname: redis
    image: redis/redis-stack
    ports:
      - 6379:6379
      - 8001:8001