version: '3.4'
name: DragaliaAPI

services:
  dragaliaapi:
    container_name: dragaliaapi
    hostname: dragaliaapi
    image: ${DOCKER_REGISTRY-}dragaliaapi
    build:
      context: .
      dockerfile: DragaliaAPI/Dockerfile
    ports:
      - "5000:80"
      - "5001:443"
    links:
      - sqlserver
    depends_on:
      sqlserver:
        condition: service_healthy
        

  sqlserver:
    container_name: sqlserver
    hostname: sqlserver
    image: "mcr.microsoft.com/mssql/server"
    environment:
      - "MSSQL_SA_PASSWORD=DragaliaLost123"
      - "ACCEPT_EULA=Y"
    ports:
      - "1433:1433"
    healthcheck:
      test: /opt/mssql-tools/bin/sqlcmd -S host.docker.internal -U SA -P $$MSSQL_SA_PASSWORD -Q "SELECT 'Test' as 'Test'" || exit 1
      interval: 5s
      retries: 3
