name: deploy

on:
  workflow_run:
    workflows: 
      - publish
    branches: 
      - develop
    types:
      - completed    

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: ssh and restart pods
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          script: kubectl rollout restart deployment/dragalia-api