name: deploy

on:
  workflow_call:
    inputs:
      github-environment:
        type: string
        required: true
        description: "GitHub environment name"

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: ${{ inputs.github-environment }}
      url: https://dawnshard.co.uk
    steps:
      - name: ssh and restart pods
        uses: appleboy/ssh-action@v0.1.6
        env:
          KUBECONFIG: $HOME/.kube/config
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script_stop: true
          envs: KUBECONFIG
          script: |
            echo $KUBECONFIG
            kubectl rollout restart deployment/${{ vars.K8S_DEPLOYMENT }} -n ${{ vars.K8S_NAMESPACE }}
            kubectl rollout status deployment/${{ vars.K8S_DEPLOYMENT }} -n ${{ vars.K8S_NAMESPACE }}
