name: publish-push

on:
  push:
    branches:
      - develop
    paths-ignore:
      - "**/*.yaml"
      - "**/*.yml"
      - "**/*.md"

env:
  HUSKY: 0

jobs:
  publish:
    uses: sapiensanatis/dragalia-api/.github/workflows/publish-base.yaml
    with:
      ref: develop
      image-tag: latest
  deploy:
    needs: publish
    uses: sapiensanatis/dragalia-api/.github/workflows/deploy.yaml
