name: "test-report"

on:
  workflow_run:
    workflows: ["test"]
    types:
      - completed

jobs:
  report:
    runs-on: ubuntu-latest
    steps:
      - name: Generate report
        uses: dorny/test-reporter@v1
        with:
          artifact: "/test-result-(.*)/"
          name: "$1"
          path: "*.trx"
          reporter: dotnet-trx
          token: "${{ secrets.PERSONAL_ACCESS_TOKEN }}"
